version: "3.8"

services:

  mongo:
      
      image: mongo:latest
      container_name: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: jmodell
        MONGO_INITDB_ROOT_PASSWORD: 5T1aBQa7        
      volumes:
        - mongo_vol:/data/db  
      ports:
        - 27077:27017

volumes:
  mongo_vol:

